# 端口号
server:
  port: 10000
# 配置
spring:
  application:
    # name:后面要有空格
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id:  goods
        uri: https://localhost:9010
        # 断言
        predicates:
        # 匹配路径转发
        - Path=/goods-service/**
